ASSEMBLY_DATA_FROM_WIKI = {
    457: {
        "district": "32",
        "name": "Vivian Cook",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Vivian E. Cook",
    },
    460: {
        "district": "35",
        "name": "Jeffrion Aubry",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jeffrion L. Aubry",
    },
    464: {
        "district": "1",
        "name": "Fred Thiele",
        "party": "I",
        "scraped_name__SANITY_CHECK": "Fred Thiele",
    },
    466: {
        "district": "4",
        "name": "Steven Englebright",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Steve Englebright",
    },
    468: {
        "district": "6",
        "name": "Philip Ramos",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Philip Ramos",
    },
    469: {
        "district": "8",
        "name": "Michael J. Fitzpatrick",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael J. Fitzpatrick",
    },
    474: {
        "district": "13",
        "name": "Charles Lavine",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Charles D. Lavine",
    },
    476: {
        "district": "15",
        "name": "Michael Montesano",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Montesano",
    },
    480: {
        "district": "14",
        "name": "David McDonough",
        "party": "R",
        "scraped_name__SANITY_CHECK": "David McDonough",
    },
    484: {
        "district": "24",
        "name": "David Weprin",
        "party": "D",
        "scraped_name__SANITY_CHECK": "David Weprin",
    },
    488: {
        "district": "28",
        "name": "Andrew Hevesi",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Andrew Hevesi",
    },
    491: {
        "district": "37",
        "name": "Catherine Nolan",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Catherine Nolan",
    },
    494: {
        "district": "41",
        "name": "Helene Weinstein",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Helene Weinstein",
    },
    498: {
        "district": "45",
        "name": "Steven Cymbrowitz",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Steven Cymbrowitz",
    },
    500: {
        "district": "47",
        "name": "William Colton",
        "party": "D",
        "scraped_name__SANITY_CHECK": "William Colton",
    },
    502: {
        "district": "49",
        "name": "Peter Abbate",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Peter J. Abbate Jr.",
    },
    511: {
        "district": "58",
        "name": "N. Nick Perry",
        "party": "D",
        "scraped_name__SANITY_CHECK": "N. Nick Perry",
    },
    516: {
        "district": "63",
        "name": "Michael Cusick",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Michael Cusick",
    },
    519: {
        "district": "66",
        "name": "Deborah Glick",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Deborah J. Glick",
    },
    520: {
        "district": "67",
        "name": "Linda Rosenthal",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Linda Rosenthal",
    },
    522: {
        "district": "69",
        "name": "Daniel O'Donnell",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Daniel J. O'Donnell",
    },
    527: {
        "district": "75",
        "name": "Richard Gottfried",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Richard N. Gottfried",
    },
    530: {
        "district": "78",
        "name": "Jose Rivera",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jose Rivera",
    },
    533: {
        "district": "81",
        "name": "Jeffrey Dinowitz",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jeffrey Dinowitz",
    },
    534: {
        "district": "82",
        "name": "Michael Benedetto",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Michael Benedetto",
    },
    535: {
        "district": "83",
        "name": "Carl Heastie",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Carl Heastie",
    },
    539: {
        "district": "89",
        "name": "J. Gary Pretlow",
        "party": "D",
        "scraped_name__SANITY_CHECK": "J. Gary Pretlow",
    },
    540: {
        "district": "88",
        "name": "Amy Paulin",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Amy Paulin",
    },
    545: {
        "district": "96",
        "name": "Kenneth Zebrowski",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Kenneth Zebrowski Jr.",
    },
    549: {
        "district": "100",
        "name": "Aileen Gunther",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Aileen Gunther",
    },
    551: {
        "district": "103",
        "name": "Kevin Cahill",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Kevin A. Cahill",
    },
    570: {
        "district": "129",
        "name": "William Magnarelli",
        "party": "D",
        "scraped_name__SANITY_CHECK": "William Magnarelli",
    },
    571: {
        "district": "127",
        "name": "Albert A. Stirpe",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Albert A. Stirpe Jr.",
    },
    574: {
        "district": "120",
        "name": "William A. Barclay",
        "party": "R",
        "scraped_name__SANITY_CHECK": "William A. Barclay",
    },
    576: {
        "district": "123",
        "name": "Donna Lupardo",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Donna Lupardo",
    },
    589: {
        "district": "139",
        "name": "Stephen Hawley",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Stephen Hawley",
    },
    591: {
        "district": "141",
        "name": "Crystal Peoples-Stokes",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Crystal Peoples-Stokes",
    },
    599: {
        "district": "148",
        "name": "Joseph Giglio",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Joseph Giglio",
    },
    608: {
        "district": "19",
        "name": "Edward Ra",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Ed Ra",
    },
    610: {
        "district": "26",
        "name": "Edward Braunstein",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Edward Braunstein",
    },
    618: {
        "district": "73",
        "name": "Dan Quart",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Dan Quart",
    },
    621: {
        "district": "95",
        "name": "Sandy Galef",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Sandy Galef",
    },
    622: {
        "district": "92",
        "name": "Thomas Abinanti",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Thomas J. Abinanti",
    },
    625: {
        "district": "106",
        "name": "Didi Barrett",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Didi Barrett",
    },
    631: {
        "district": "117",
        "name": "Kenneth Blankenbush",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Ken Blankenbush",
    },
    633: {
        "district": "138",
        "name": "Harry B. Bronson",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Harry Bronson",
    },
    635: {
        "district": "132",
        "name": "Philip Palmesano",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Phil Palmesano",
    },
    636: {
        "district": "124",
        "name": "Christopher Friend",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Christopher S. Friend",
    },
    642: {
        "district": "150",
        "name": "Andrew Goodell",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Andy Goodell",
    },
    655: {
        "district": "53",
        "name": "Maritza Davila",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Maritza Davila",
    },
    656: {
        "district": "147",
        "name": "David DiPietro",
        "party": "R",
        "scraped_name__SANITY_CHECK": "David DiPietro",
    },
    657: {
        "district": "109",
        "name": "Patricia Fahy",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Patricia Fahy",
    },
    659: {
        "district": "40",
        "name": "Ron Kim",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Ron Kim",
    },
    660: {
        "district": "105",
        "name": "Kieran Michael Lalor",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Kieran Lalor",
    },
    662: {
        "district": "108",
        "name": "John T. McDonald III",
        "party": "D",
        "scraped_name__SANITY_CHECK": "John T. McDonald III",
    },
    665: {
        "district": "91",
        "name": "Steven Otis",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Steven Otis",
    },
    669: {
        "district": "25",
        "name": "Nily Rozic",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Nily Rozic",
    },
    670: {
        "district": "111",
        "name": "Angelo Santabarbara",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Angelo Santabarbara",
    },
    673: {
        "district": "22",
        "name": "Michaelle C. Solages",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Michaelle C. Solages",
    },
    675: {
        "district": "110",
        "name": "Phil Steck",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Phillip Steck",
    },
    886: {
        "district": "113",
        "name": "Carrie Woerner",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Carrie Woerner",
    },
    896: {
        "district": "55",
        "name": "Latrice Walker",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Latrice Walker",
    },
    898: {
        "district": "42",
        "name": "Rodneyse Bichotte Hermelyn",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Rodneyse Bichotte Hermelyn",
    },
    900: {
        "district": "54",
        "name": "Erik Dilan",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Erik Martin Dilan",
    },
    901: {
        "district": "11",
        "name": "Kimberly Jean-Pierre",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Kimberly Jean-Pierre",
    },
    902: {
        "district": "77",
        "name": "Latoya Joyner",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Latoya Joyner",
    },
    906: {
        "district": "76",
        "name": "Rebecca Seawright",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Rebecca Seawright",
    },
    907: {
        "district": "52",
        "name": "Jo Anne Simon",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jo Anne Simon",
    },
    908: {
        "district": "98",
        "name": "Karl Brabenec",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Karl A. Brabenec",
    },
    912: {
        "district": "43",
        "name": "Diana Richardson",
        "party": None,
        "scraped_name__SANITY_CHECK": "Diana Richardson",
    },
    1089: {
        "district": "29",
        "name": "Alicia Hyndman",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Alicia Hyndman",
    },
    1105: {
        "district": "128",
        "name": "Pamela J. Hunter",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Pamela Hunter",
    },
    1115: {
        "district": "20",
        "name": "Melissa Miller",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Melissa Miller",
    },
    1116: {
        "district": "59",
        "name": "Jaime R. Williams",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jaime Williams",
    },
    1118: {
        "district": "33",
        "name": "Clyde Vanel",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Clyde Vanel",
    },
    1119: {
        "district": "30",
        "name": "Brian Barnwell",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Brian Barnwell",
    },
    1120: {
        "district": "115",
        "name": "Billy Jones",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Billy Jones",
    },
    1122: {
        "district": "44",
        "name": "Robert C. Carroll",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Robert Carroll",
    },
    1123: {
        "district": "94",
        "name": "Kevin M. Byrne",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Kevin Byrne",
    },
    1125: {
        "district": "101",
        "name": "Brian D. Miller",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Brian Miller",
    },
    1126: {
        "district": "144",
        "name": "Michael J. Norris",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Norris",
    },
    1127: {
        "district": "112",
        "name": "Mary Beth Walsh",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Mary Beth Walsh",
    },
    1128: {
        "district": "70",
        "name": "Inez E. Dickens",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Inez Dickens",
    },
    1131: {
        "district": "23",
        "name": "Stacey Pheffer Amato",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Stacey Pheffer Amato",
    },
    1132: {
        "district": "65",
        "name": "Yuh-Line Niou",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Yuh-Line Niou",
    },
    1133: {
        "district": "143",
        "name": "Monica P. Wallace",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Monica P. Wallace",
    },
    1135: {
        "district": "145",
        "name": "Angelo J. Morinello",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Angelo Morinello",
    },
    1139: {
        "district": "27",
        "name": "Daniel Rosenthal",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Daniel Rosenthal",
    },
    1141: {
        "district": "71",
        "name": "Al Taylor",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Al Taylor",
    },
    1144: {
        "district": "74",
        "name": "Harvey Epstein",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Harvey Epstein",
    },
    1146: {
        "district": "80",
        "name": "Nathalia Fernandez",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Nathalia Fernandez",
    },
    1147: {
        "district": "10",
        "name": "Steve Stern",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Steve Stern",
    },
    1148: {
        "district": "5",
        "name": "Doug Smith",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Douglas M. Smith",
    },
    1150: {
        "district": "17",
        "name": "John K. Mikulin",
        "party": "R",
        "scraped_name__SANITY_CHECK": "John Mikulin",
    },
    1151: {
        "district": "107",
        "name": "Jake Ashby",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Jacob Ashby",
    },
    1152: {
        "district": "102",
        "name": "Chris Tague",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Christopher Tague",
    },
    1238: {
        "district": "3",
        "name": "Joe DeStefano",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Joe DeStefano",
    },
    1240: {
        "district": "18",
        "name": "Taylor Darling",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Taylor Darling",
    },
    1241: {
        "district": "21",
        "name": "Judy Griffin",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Judy Griffin",
    },
    1242: {
        "district": "39",
        "name": "Catalina Cruz",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Catalina Cruz",
    },
    1243: {
        "district": "48",
        "name": "Simcha Eichenstein",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Simcha Eichenstein",
    },
    1244: {
        "district": "61",
        "name": "Charles Fall",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Charles Fall",
    },
    1245: {
        "district": "62",
        "name": "Mike Reilly",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Reilly",
    },
    1246: {
        "district": "99",
        "name": "Colin Schmitt",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Colin Schmitt",
    },
    1247: {
        "district": "116",
        "name": "Mark Walczyk",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Mark Walczyk",
    },
    1248: {
        "district": "118",
        "name": "Robert Smullen",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Robert Smullen",
    },
    1249: {
        "district": "119",
        "name": "Marianne Buttenschon",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Marianne Buttenschon",
    },
    1250: {
        "district": "121",
        "name": "John Salka",
        "party": "R",
        "scraped_name__SANITY_CHECK": "John Salka",
    },
    1251: {
        "district": "130",
        "name": "Brian Manktelow",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Brian Manktelow",
    },
    1252: {
        "district": "133",
        "name": "Marjorie Byrnes",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Marjorie Byrnes",
    },
    1254: {
        "district": "142",
        "name": "Patrick Burke",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Patrick B. Burke",
    },
    1255: {
        "district": "146",
        "name": "Karen McMahon",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Karen McMahon",
    },
    1256: {
        "district": "46",
        "name": "Mathylde Frontus",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Mathylde Frontus",
    },
    1257: {
        "district": "87",
        "name": "Karines Reyes",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Karines Reyes",
    },
    1258: {
        "district": "90",
        "name": "Nader sayegh",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Nader Sayegh",
    },
    1259: {
        "district": "104",
        "name": "Jonathan Jacobson",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jonathan Jacobson",
    },
    1459: {
        "district": "31",
        "name": "Khaleel Anderson",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Khaleel Anderson",
    },
    1460: {
        "district": "136",
        "name": "Sarah Clark",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Sarah Clark",
    },
    1461: {
        "district": "12",
        "name": "Keith Brown",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Keith Brown",
    },
    1462: {
        "district": "137",
        "name": "Demond Meeks",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Demond Meeks",
    },
    1463: {
        "district": "85",
        "name": "Kenny Burgos",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Kenny Burgos",
    },
    1464: {
        "district": "2",
        "name": "Jodi Giglio",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Jodi Giglio",
    },
    1465: {
        "district": "7",
        "name": "Jerett Gandolfo",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Jarett Gandolfo",
    },
    1466: {
        "district": "9",
        "name": "Michael Durso",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Durso",
    },
    1467: {
        "district": "16",
        "name": "Gina Sillitti",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Gina Sillitti",
    },
    1468: {
        "district": "34",
        "name": "Jessica Gonzalez-Rojas",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jessica González-Rojas",
    },
    1469: {
        "district": "36",
        "name": "Zohran Mamdani",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Zohran Mamdani",
    },
    1470: {
        "district": "38",
        "name": "Jenifer Rajkumar",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jenifer Rajkumar",
    },
    1471: {
        "district": "50",
        "name": "Emily Gallagher",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Emily Gallagher",
    },
    1472: {
        "district": "51",
        "name": "Marcela Mitaynes",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Marcela Mitaynes",
    },
    1473: {
        "district": "56",
        "name": "Stefani Zinerman",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Stefani Zinerman",
    },
    1474: {
        "district": "57",
        "name": "Phara Souffrant Forrest",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Phara Souffrant Forrest",
    },
    1475: {
        "district": "64",
        "name": "Michael Tannousis",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Tannousis",
    },
    1476: {
        "district": "79",
        "name": "Chantel Jackson",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Chantel Jackson",
    },
    1477: {
        "district": "84",
        "name": "Amanda Septimo",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Amanda Septimo",
    },
    1478: {
        "district": "93",
        "name": "Chris Burdick",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Chris Burdick",
    },
    1479: {
        "district": "97",
        "name": "Michael Lawler",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Michael Lawler",
    },
    1480: {
        "district": "114",
        "name": "Matthew Simpson",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Matt Simpson",
    },
    1481: {
        "district": "122",
        "name": "Joe Angelino",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Joe Angelino",
    },
    1482: {
        "district": "125",
        "name": "Anna Kelles",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Anna Kelles",
    },
    1483: {
        "district": "126",
        "name": "John Lemondes",
        "party": "R",
        "scraped_name__SANITY_CHECK": "John Lemondes Jr.",
    },
    1484: {
        "district": "131",
        "name": "Jeff Gallahan",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Jeff Gallahan",
    },
    1485: {
        "district": "134",
        "name": "Josh Jensen",
        "party": "R",
        "scraped_name__SANITY_CHECK": "Josh Jensen",
    },
    1486: {
        "district": "135",
        "name": "Jen Lunsford",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jennifer Lunsford",
    },
    1487: {
        "district": "140",
        "name": "William Conrad",
        "party": "D",
        "scraped_name__SANITY_CHECK": "William Conrad III",
    },
    1488: {
        "district": "149",
        "name": "Jonathan Rivera",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Jonathan Rivera",
    },
    1503: {
        "district": "86",
        "name": "Yudelka Tapia",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Yudelka Tapia",
    },
    1505: {
        "district": "68",
        "name": "Eddie Gibbs",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Eddie Gibbs",
    },
    1506: {
        "district": "72",
        "name": "Manny De Los Santos",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Manny De Los Santos",
    },
    1507: {
        "district": "60",
        "name": "Nikki Lucas",
        "party": "D",
        "scraped_name__SANITY_CHECK": "Nikki Lucas",
    },
}
