"""
Contains data on legislators that is not provided by the API. Although st sync
most data that we can from the API, we expect these values to change rarely and
it's fine to have them be fixed.
"""

D = "D"
R = "R"

# The API does provide "name", but we have it here too so allow overriding
# the rendering of the name, and also because it makes this dict much easier
# to read.
COUNCIL_DATA_BY_LEGISLATOR_ID = {
    7739: {
        "name": "Adrienne E. Adams",
        "twitter": "AdrienneEAdams1",
        "party": "D",
        "borough": "Queens",
    },
    7747: {
        "name": "Alicka Ampry-Samuel",
        "twitter": "CMAlickaASamuel",
        "party": "D",
        "borough": "Brooklyn",
    },
    7742: {
        "name": "Diana Ayala",
        "twitter": "DianaAyalaNYC",
        "party": "D",
        "borough": "Manhattan and Bronx",
    },
    7623: {
        "name": "Inez D. Barron",
        "twitter": "CMInezDBarron",
        "party": "D",
        "borough": "Brooklyn",
    },
    7264: {
        "name": "Joseph C. Borelli",
        "twitter": "JoeBorelliNYC",
        "party": "R",
        "borough": "Staten Island",
    },
    7748: {
        "name": "Justin L. Brannan",
        "twitter": "JustinBrannan",
        "party": "D",
        "borough": "Brooklyn",
    },
    7561: {
        "name": "Fernando Cabrera ",
        "twitter": "FCabreraNY",
        "party": "D",
        "borough": "Bronx",
    },
    7562: {
        "name": "Margaret S. Chin",
        "twitter": "CM_MargaretChin",
        "party": "D",
        "borough": "Manhattan",
    },
    7604: {
        "name": "Robert E. Cornegy, Jr.",
        "twitter": "rc4bk",
        "party": "D",
        "borough": "Brooklyn",
    },
    7628: {
        "name": "Laurie A. Cumbo",
        "twitter": "cmlauriecumbo",
        "party": "D",
        "borough": "Brooklyn",
    },
    7744: {
        "name": "Ruben Diaz, Sr.",
        "twitter": "revrubendiaz",
        "party": "D",
        "borough": "Bronx",
    },
    7563: {
        "name": "Daniel Dromm",
        "twitter": "Dromm25",
        "party": "D",
        "borough": "Queens",
    },
    7113: {
        "name": "Mathieu Eugene",
        "twitter": "CMMathieuEugene",
        "party": "D",
        "borough": "Brooklyn",
    },
    7622: {
        "name": "Vanessa L. Gibson",
        "twitter": "Vanessalgibson",
        "party": "D",
        "borough": "Bronx",
    },
    7743: {
        "name": "Mark Gjonaj ",
        "twitter": "MarkGjonajNY",
        "party": "D",
        "borough": "Bronx",
    },
    7691: {
        "name": "Barry S. Grodenchik",
        "twitter": "BarryGrodenchik",
        "party": "D",
        "borough": "Queens",
    },
    7746: {
        "name": "Robert F. Holden",
        "twitter": "BobHoldenNYC",
        "party": "D",
        "borough": "Queens",
    },
    7631: {
        "name": "Corey D. Johnson",
        "twitter": "NYCSpeakerCoJo",
        "party": "D",
        "borough": "Manhattan",
    },
    7632: {
        "name": "Ben Kallos",
        "twitter": "BenKallos",
        "party": "D",
        "borough": "Manhattan",
    },
    7565: {
        "name": "Peter A. Koo",
        "twitter": "CMPeterKoo",
        "party": "D",
        "borough": "Queens",
    },
    386: {
        "name": "Karen Koslowitz",
        "twitter": "CMKoslowitz",
        "party": "D",
        "borough": "Queens",
    },
    7566: {
        "name": "Brad S. Lander",
        "twitter": "bradlander",
        "party": "D",
        "borough": "Brooklyn",
    },
    7567: {
        "name": "Stephen T. Levin",
        "twitter": "StephenLevin33",
        "party": "D",
        "borough": "Brooklyn",
    },
    7634: {
        "name": "Mark Levine",
        "twitter": "MarkLevineNYC",
        "party": "D",
        "borough": "Manhattan",
    },
    7635: {
        "name": "Alan N. Maisel",
        "twitter": None,
        "party": "D",
        "borough": "Brooklyn",
    },
    5953: {
        "name": "Steven Matteo",
        "twitter": "StevenMatteo",
        "party": "R",
        "borough": "Staten Island",
    },
    7636: {
        "name": "Carlos Menchaca",
        "twitter": "cmenchaca",
        "party": "D",
        "borough": "Brooklyn",
    },
    7637: {
        "name": "I. Daneek Miller",
        "twitter": "IDaneekMiller",
        "party": "D",
        "borough": "Queens",
    },
    7745: {
        "name": "Francisco P. Moya",
        "twitter": "FranciscoMoyaNY",
        "party": "D",
        "borough": "Queens",
    },
    430: {
        "name": "Bill Perkins",
        "twitter": "BillPerkinsNYC",
        "party": "D",
        "borough": "Manhattan",
    },
    7741: {
        "name": "Keith Powers",
        "twitter": "KeithPowersNYC",
        "party": "D",
        "borough": "Manhattan",
    },
    7638: {
        "name": "Antonio Reynoso",
        "twitter": "ReynosoBrooklyn",
        "party": "D",
        "borough": "Brooklyn",
    },
    7740: {
        "name": "Carlina Rivera ",
        "twitter": "CarlinaRivera",
        "party": "D",
        "borough": "Manhattan",
    },
    7541: {
        "name": "Ydanis A. Rodriguez",
        "twitter": "ydanis",
        "party": "D",
        "borough": "Manhattan",
    },
    7568: {
        "name": "Deborah L. Rose",
        "twitter": "CMDebiRose",
        "party": "D",
        "borough": "Staten Island",
    },
    7639: {
        "name": "Helen K. Rosenthal",
        "twitter": "HelenRosenthal",
        "party": "D",
        "borough": "Manhattan",
    },
    7714: {
        "name": "Rafael Salamanca, Jr.",
        "twitter": "Salamancajr80",
        "party": "D",
        "borough": "Bronx",
    },
    7641: {
        "name": "Mark Treyger",
        "twitter": "MarkTreyger718",
        "party": "D",
        "borough": "Brooklyn",
    },
    7510: {
        "name": "Eric A. Ulrich",
        "twitter": "eric_ulrich",
        "party": "R",
        "borough": "Queens",
    },
    7642: {
        "name": "Paul A. Vallone",
        "twitter": "PaulVallone",
        "party": "D",
        "borough": "Queens",
    },
    7569: {
        "name": "James G. Van Bramer",
        "twitter": "JimmyVanBramer",
        "party": "D",
        "borough": "Queens",
    },
    7749: {
        "name": "Kalman Yeger",
        "twitter": "KalmanYeger",
        "party": "D",
        "borough": "Brooklyn",
    },
    7780: {
        "name": "Public Advocate Jumaane Williams",
        "twitter": "JumaaneWilliams",
        "party": "D",
        "borough": "",
    },
    7785: {
        "name": "Farah N. Louis",
        "twitter": "CMFarahLouis",
        "party": "D",
        "borough": "Brooklyn",
    },
    7793: {
        "name": "Darma V. Diaz",
        "twitter": None,
        "party": "D",
        "borough": "Brooklyn",
    },
    7794: {
        "name": "Kevin C. Riley",
        "twitter": "CMKevinCRiley",
        "party": "D",
        "borough": "Bronx",
    },
    5273: {
        "name": "James F. Gennaro",
        "twitter": "JimGennaro",
        "party": "D",
        "borough": "Queens",
    },
    7796: {
        "name": "Selvena N. Brooks-Powers",
        "twitter": "Powers4Queens",
        "party": "D",
        "borough": "Queens",
    },
    7799: {
        "name": "Eric Dinowitz",
        "twitter": "EricDinowitz",
        "party": "D",
        "borough": "Bronx",
    },
    7798: {
        "name": "Oswald Feliz",
        "twitter": "OswaldFeliz",
        "party": "D",
        "borough": "Bronx",
    },
    # New peoople in 2022:
    7804: {
        "name": "Shaun Abreu",
        "borough": "Manhattan",
        "twitter": "shaunabreu",
        "party": "D",
    },
    6272: {
        "name": "Darlene Mealy",
        "borough": "Brooklyn",
        "twitter": "DarleneMealy55",
        "party": "D",
    },
    7822: {
        "name": "Crystal Hudson",
        "borough": "Brooklyn",
        "twitter": "crystalrhudson",
        "party": "D",
    },
    5288: {
        "name": "Charles Barron",
        "borough": "Brooklyn",
        "twitter": "CharlesBarron12",
        "party": "D",
    },
    7818: {
        "name": "Lynn C. Schulman",
        "borough": "Queens",
        "twitter": "Lynn4NYC",
        "party": "D",
    },
    7819: {
        "name": "Joann Ariola ",
        "borough": "Queens",
        "twitter": "JoannAriola32",
        "party": "R",
    },
    7801: {
        "name": "Christopher Marte",
        "borough": "Manhattan",
        "twitter": "ChrisMarteNYC",
        "party": "D",
    },
    7826: {
        "name": "Shahana K. Hanif",
        "borough": "Brooklyn",
        "twitter": "ShahanaFromBK",
        "party": "D",
    },
    7820: {
        "name": "Lincoln Restler",
        "borough": "Brooklyn",
        "twitter": "LincolnRestler",
        "party": "D",
    },
    7814: {
        "name": "Linda Lee",
        "borough": "Queens",
        "twitter": "LindaLeeforNYC",
        "party": "D",
    },
    7811: {
        "name": "Vickie Paladino",
        "borough": "Queens",
        "twitter": "VickieforNYC",
        "party": "R",
    },
    7810: {
        "name": "Amanda Farías ",
        "borough": "Bronx",
        "twitter": "AmandaFariasNYC",
        "party": "D",
    },
    7831: {
        "name": "Inna Vernikov",
        "borough": "Brooklyn",
        "twitter": "InnaVernikov",
        "party": "R",
    },
    7806: {
        "name": "Carmen N. De La Rosa",
        "borough": "Manhattan",
        "twitter": "CnDelarosa",
        "party": "D",
    },
    7812: {
        "name": "Sandra Ung",
        "borough": "Queens",
        "twitter": "SandraForNY1",
        "party": "D",
    },
    7829: {
        "name": "Mercedes Narcisse",
        "borough": "Brooklyn",
        "twitter": "MercedesNarciss",
        "party": "D",
    },
    7809: {
        "name": "Althea V.  Stevens",
        "borough": "Bronx",
        "twitter": "althea4thebx",
        "party": "D",
    },
    7823: {
        "name": "Chi A. Ossé",
        "borough": "Brooklyn",
        "twitter": "OsseChi",
        "party": "D",
    },
    7802: {
        "name": "Erik D. Bottcher",
        "borough": "Manhattan",
        "twitter": "ebottcher",
        "party": "D",
    },
    7805: {
        "name": "Kristin Richardson Jordan",
        "borough": "Manhattan",
        "twitter": "Kristin4Harlem",
        "party": "D",
    },
    7830: {
        "name": "Ari Kagan",
        "borough": "Brooklyn",
        "twitter": "AriKagan47",
        "party": "D",
    },
    7825: {
        "name": "Alexa Avilés ",
        "borough": "Brooklyn",
        "twitter": "alexaforcouncil",
        "party": "D",
    },
    7803: {
        "name": "Julie Menin",
        "borough": "Manhattan",
        "twitter": "JulieMenin",
        "party": "D",
    },
    7815: {
        "name": "Shekar Krishnan",
        "borough": "Queens",
        "twitter": "VoteShekar",
        "party": "D",
    },
    7817: {
        "name": "Nantasha M. Williams",
        "borough": "Queens",
        "twitter": "CMNantashaW",
        "party": "D",
    },
    7821: {
        "name": "Jennifer Gutiérrez",
        "borough": "Brooklyn",
        "twitter": "JenGutierrezNYC",
        "party": "D",
    },
    7827: {
        "name": "Rita C. Joseph",
        "borough": "Brooklyn",
        "twitter": "RitaJosephNYC",
        "party": "D",
    },
    7813: {
        "name": "Tiffany Cabán",
        "borough": "Queens",
        "twitter": "tiffany_caban",
        "party": "D",
    },
    7833: {
        "name": "David M. Carr",
        "borough": "Staten Island",
        "twitter": "DMCarr",
        "party": "R",
    },
    7832: {
        "name": "Kamillah Hanks",
        "borough": "Staten Island",
        "twitter": "KamillahMHanks",
        "party": "D",
    },
    7807: {
        "name": "Marjorie Velázquez",
        "borough": "Bronx",
        "twitter": "mvelaznyc",
        "party": "D",
    },
    7808: {
        "name": "Pierina Ana Sanchez",
        "borough": "Bronx",
        "twitter": "PiSanchezNYC",
        "party": "D",
    },
    7824: {
        "name": "Sandy Nurse",
        "borough": "Brooklyn",
        "twitter": "SandyForCouncil",
        "party": "D",
    },
    7816: {
        "name": "Julie Won",
        "borough": "Queens",
        "twitter": "juliej_won",
        "party": "D",
    },
    5259: {
        "name": "Gale A. Brewer",
        "borough": "Manhattan",
        "twitter": "GaleABrewer",
        "party": "D",
    },
}
