SENATE_DATA_FROM_WIKI = {
    372: {
        "counties": ["Albany", "Rensselaer"],
        "district": "44",
        "name": "Neil D. Breslin",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Neil Breslin",
    },
    373: {
        "counties": ["New York (Manhattan)", "Bronx"],
        "district": "29",
        "name": "José M. Serrano",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "José M. Serrano",
    },
    377: {
        "counties": ["Bronx"],
        "district": "33",
        "name": "Gustavo Rivera",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Gustavo Rivera",
    },
    383: {
        "counties": ["Queens"],
        "district": "12",
        "name": "Michael Gianaris",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Michael Gianaris",
    },
    384: {
        "counties": ["Queens"],
        "district": "15",
        "name": "Joseph P. Addabbo Jr.",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Joseph Addabbo Jr.",
    },
    393: {
        "counties": ["Lewis", "Oneida", "St. Lawrence"],
        "district": "47",
        "name": "Joseph A. Griffo",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Joseph Griffo",
    },
    396: {
        "counties": ["Westchester"],
        "district": "35",
        "name": "Andrea Stewart-Cousins",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Andrea Stewart-Cousins",
    },
    400: {
        "counties": ["Queens"],
        "district": "16",
        "name": "Toby Ann Stavisky",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Toby Ann Stavisky",
    },
    401: {
        "counties": ["New York (Manhattan)"],
        "district": "28",
        "name": "Liz Krueger",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Liz Krueger",
    },
    403: {
        "counties": ["Kings (Brooklyn)", "Richmond (Staten Island)"],
        "district": "23",
        "name": "Diane J. Savino",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Diane Savino",
    },
    409: {
        "counties": ["Richmond (Staten Island)"],
        "district": "24",
        "name": "Andrew J Lanza",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Andrew Lanza",
    },
    415: {
        "counties": ["Chemung", "Schuyler", "Steuben", "Tompkins", "Yates"],
        "district": "58",
        "name": "Thomas F. O'Mara",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Tom O'Mara",
    },
    416: {
        "counties": ["Kings (Brooklyn)"],
        "district": "21",
        "name": "Kevin S. Parker",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Kevin Parker",
    },
    423: {
        "counties": ["Jefferson", "Oswego", "St. Lawrence"],
        "district": "48",
        "name": "Patty Ritchie",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Patty Ritchie",
    },
    427: {
        "counties": ["Erie", "Livingston", "Monroe", "Wyoming"],
        "district": "59",
        "name": "Patrick M. Gallivan",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Patrick M. Gallivan",
    },
    429: {
        "counties": ["Erie"],
        "district": "63",
        "name": "Timothy M. Kennedy",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Timothy M. Kennedy",
    },
    432: {
        "counties": ["Queens"],
        "district": "10",
        "name": "James Sanders Jr.",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "James Sanders Jr.",
    },
    433: {
        "counties": ["Suffolk"],
        "district": "4",
        "name": "Phil Boyle",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Phil Boyle",
    },
    438: {
        "counties": ["New York (Manhattan)"],
        "district": "27",
        "name": "Brad Hoylman",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Brad Hoylman",
    },
    439: {
        "counties": ["Kings (Brooklyn)"],
        "district": "17",
        "name": "Simcha Felder",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Simcha Felder",
    },
    885: {
        "counties": ["Monroe", "Niagara", "Orleans"],
        "district": "62",
        "name": "Robert Ortt",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Rob Ortt",
    },
    888: {
        "counties": ["Queens"],
        "district": "14",
        "name": "Leroy Comrie",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Leroy Comrie",
    },
    890: {
        "counties": ["Dutchess", "Putnam"],
        "district": "41",
        "name": "Susan Serino",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Sue Serino",
    },
    913: {
        "counties": ["Broome", "Chenango", "Delaware", "Tioga"],
        "district": "52",
        "name": "Fredrick J Akshar II",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Fred Akshar",
    },
    914: {
        "counties": ["Kings (Brooklyn)"],
        "district": "19",
        "name": "Roxanne J Persaud",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Roxanne Persaud",
    },
    918: {
        "counties": ["Nassau"],
        "district": "9",
        "name": "Todd Kaminsky",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Todd Kaminsky",
    },
    951: {
        "counties": [
            "Cayuga",
            "Monroe",
            "Ontario",
            "Seneca",
            "Tompkins",
            "Wayne",
        ],
        "district": "54",
        "name": "Pamela Helming",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Pam Helming",
    },
    1101: {
        "counties": ["Nassau", "Suffolk"],
        "district": "8",
        "name": "John E. Brooks",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "John Brooks",
    },
    1102: {
        "counties": ["Bronx", "Westchester"],
        "district": "36",
        "name": "Jamaal Bailey",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Jamaal Bailey",
    },
    1103: {
        "counties": [
            "Fulton",
            "Hamilton",
            "Herkimer",
            "Saratoga",
            "Schenectady",
        ],
        "district": "49",
        "name": "James Tedisco",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Jim Tedisco",
    },
    1140: {
        "counties": ["Kings (Brooklyn)", "New York (Manhattan)"],
        "district": "26",
        "name": "Brian Kavanagh",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Brian P. Kavanagh",
    },
    1142: {
        "counties": ["Bronx"],
        "district": "32",
        "name": "Luis R. Sepúlveda",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Luis R. Sepúlveda",
    },
    1143: {
        "counties": ["Westchester"],
        "district": "37",
        "name": "Shelley Mayer",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Shelley Mayer",
    },
    1222: {
        "counties": ["Nassau", "Suffolk"],
        "district": "5",
        "name": "Jim Gaughran",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Jim Gaughran",
    },
    1223: {
        "counties": ["Nassau"],
        "district": "6",
        "name": "Kevin Thomas",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Kevin Thomas",
    },
    1224: {
        "counties": ["Nassau"],
        "district": "7",
        "name": "Anna Kaplan",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Anna Kaplan",
    },
    1225: {
        "counties": ["Queens"],
        "district": "11",
        "name": "John Liu",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "John Liu",
    },
    1226: {
        "counties": ["Queens"],
        "district": "13",
        "name": "Jessica Ramos",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Jessica Ramos",
    },
    1227: {
        "counties": ["Kings (Brooklyn)"],
        "district": "18",
        "name": "Julia Salazar",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Julia Salazar",
    },
    1228: {
        "counties": ["Kings (Brooklyn)"],
        "district": "20",
        "name": "Zellnor Myrie",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Zellnor Myrie",
    },
    1229: {
        "counties": ["Kings (Brooklyn)"],
        "district": "22",
        "name": "Andrew Gounardes",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Andrew Gounardes",
    },
    1230: {
        "counties": ["New York (Manhattan)"],
        "district": "31",
        "name": "Robert Jackson",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Robert Jackson",
    },
    1231: {
        "counties": ["Bronx", "Westchester"],
        "district": "34",
        "name": "Alessandra Biaggi",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Alessandra Biaggi",
    },
    1232: {
        "counties": ["Orange", "Rockland", "Ulster"],
        "district": "39",
        "name": "James Skoufis",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "James Skoufis",
    },
    1233: {
        "counties": ["Dutchess", "Putnam", "Westchester"],
        "district": "40",
        "name": "Pete Harckham",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Peter Harckham",
    },
    1235: {
        "counties": ["Columbia", "Rensselaer", "Saratoga", "Washington"],
        "district": "43",
        "name": "Daphne Jordan",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Daphne Jordan",
    },
    1237: {
        "counties": ["Madison", "Oneida", "Onondaga"],
        "district": "53",
        "name": "Rachel May",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Rachel May",
    },
    1370: {
        "counties": ["Allegany", "Cattaraugus", "Chautauqua", "Livingston"],
        "district": "57",
        "name": "George Borrello",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "George Borrello",
    },
    1489: {
        "counties": ["Suffolk"],
        "district": "1",
        "name": "Anthony H. Palumbo",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Anthony Palumbo",
    },
    1490: {
        "counties": [
            "Clinton",
            "Essex",
            "Franklin",
            "Saint Lawrence",
            "Warren",
            "Washington",
        ],
        "district": "45",
        "name": "Dan Stec",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Dan Stec",
    },
    1491: {
        "counties": ["Erie"],
        "district": "60",
        "name": "Sean Ryan",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Sean Ryan",
    },
    1492: {
        "counties": ["Suffolk"],
        "district": "2",
        "name": "Mario Mattera",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Mario Mattera",
    },
    1493: {
        "counties": ["Suffolk"],
        "district": "3",
        "name": "Alexis Weik",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Alexis Weik",
    },
    1494: {
        "counties": ["Kings (Brooklyn)"],
        "district": "25",
        "name": "Jabari Brisport",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Jabari Brisport",
    },
    1495: {
        "counties": ["Rockland", "Westchester"],
        "district": "38",
        "name": "Elijah Reichlin-Melnick",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Elijah Reichlin-Melnick",
    },
    1496: {
        "counties": ["Delaware", "Orange", "Sullivan", "Ulster"],
        "district": "42",
        "name": "Mike Martucci",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Mike Martucci",
    },
    1497: {
        "counties": [
            "Albany",
            "Greene",
            "Montgomery",
            "Schenectady",
            "Ulster",
        ],
        "district": "46",
        "name": "Michelle Hinchey",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Michelle Hinchey",
    },
    1498: {
        "counties": ["Cayuga", "Onondaga"],
        "district": "50",
        "name": "John Mannion",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "John Mannion",
    },
    1499: {
        "counties": [
            "Cayuga",
            "Chenango",
            "Cortland",
            "Delaware",
            "Herkimer",
            "Otsego",
            "Schoharie",
            "Tompkins",
            "Ulster",
        ],
        "district": "51",
        "name": "Peter Oberacker",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Peter Oberacker",
    },
    1500: {
        "counties": ["Monroe", "Ontario"],
        "district": "55",
        "name": "Samra Brouk",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Samra Brouk",
    },
    1501: {
        "counties": ["Monroe"],
        "district": "56",
        "name": "Jeremy Cooney",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Jeremy Cooney",
    },
    1502: {
        "counties": ["Erie", "Genesee", "Monroe"],
        "district": "61",
        "name": "Edward Rath",
        "party": "R",
        "wiki_scraped_name__SANITY_CHECK": "Edward Rath III",
    },
    1504: {
        "counties": ["New York (Manhattan)"],
        "district": "30",
        "name": "Cordell Cleare",
        "party": "D",
        "wiki_scraped_name__SANITY_CHECK": "Cordell Cleare",
    },
}
