"""Change column names

Revision ID: 0a7676594ecb
Revises: 427207c44b00
Create Date: 2022-01-11 09:47:49.768687

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0a7676594ecb'
down_revision = '427207c44b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly_sponsorships', sa.Column('person_id', src.models.UUID(as_uuid=True), nullable=False))
    op.add_column('assembly_sponsorships', sa.Column('bill_id', src.models.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_assembly_sponsorships_assembly_bill_id', table_name='assembly_sponsorships')
    op.drop_index('ix_assembly_sponsorships_assembly_member_id', table_name='assembly_sponsorships')
    op.create_index(op.f('ix_assembly_sponsorships_bill_id'), 'assembly_sponsorships', ['bill_id'], unique=False)
    op.create_index(op.f('ix_assembly_sponsorships_person_id'), 'assembly_sponsorships', ['person_id'], unique=False)
    op.drop_constraint('assembly_sponsorships_assembly_member_id_fkey', 'assembly_sponsorships', type_='foreignkey')
    op.drop_constraint('assembly_sponsorships_assembly_bill_id_fkey', 'assembly_sponsorships', type_='foreignkey')
    op.create_foreign_key(None, 'assembly_sponsorships', 'assembly_members', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'assembly_sponsorships', 'assembly_bills', ['bill_id'], ['bill_id'])
    op.drop_column('assembly_sponsorships', 'assembly_bill_id')
    op.drop_column('assembly_sponsorships', 'assembly_member_id')
    op.add_column('senate_sponsorships', sa.Column('person_id', src.models.UUID(as_uuid=True), nullable=False))
    op.add_column('senate_sponsorships', sa.Column('bill_id', src.models.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_senate_sponsorships_senate_bill_id', table_name='senate_sponsorships')
    op.drop_index('ix_senate_sponsorships_senator_id', table_name='senate_sponsorships')
    op.create_index(op.f('ix_senate_sponsorships_bill_id'), 'senate_sponsorships', ['bill_id'], unique=False)
    op.create_index(op.f('ix_senate_sponsorships_person_id'), 'senate_sponsorships', ['person_id'], unique=False)
    op.drop_constraint('senate_sponsorships_senator_id_fkey', 'senate_sponsorships', type_='foreignkey')
    op.drop_constraint('senate_sponsorships_senate_bill_id_fkey', 'senate_sponsorships', type_='foreignkey')
    op.create_foreign_key(None, 'senate_sponsorships', 'senators', ['person_id'], ['person_id'])
    op.create_foreign_key(None, 'senate_sponsorships', 'senate_bills', ['bill_id'], ['bill_id'])
    op.drop_column('senate_sponsorships', 'senator_id')
    op.drop_column('senate_sponsorships', 'senate_bill_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senate_sponsorships', sa.Column('senate_bill_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('senate_sponsorships', sa.Column('senator_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'senate_sponsorships', type_='foreignkey')
    op.drop_constraint(None, 'senate_sponsorships', type_='foreignkey')
    op.create_foreign_key('senate_sponsorships_senate_bill_id_fkey', 'senate_sponsorships', 'senate_bills', ['senate_bill_id'], ['bill_id'])
    op.create_foreign_key('senate_sponsorships_senator_id_fkey', 'senate_sponsorships', 'senators', ['senator_id'], ['person_id'])
    op.drop_index(op.f('ix_senate_sponsorships_person_id'), table_name='senate_sponsorships')
    op.drop_index(op.f('ix_senate_sponsorships_bill_id'), table_name='senate_sponsorships')
    op.create_index('ix_senate_sponsorships_senator_id', 'senate_sponsorships', ['senator_id'], unique=False)
    op.create_index('ix_senate_sponsorships_senate_bill_id', 'senate_sponsorships', ['senate_bill_id'], unique=False)
    op.drop_column('senate_sponsorships', 'bill_id')
    op.drop_column('senate_sponsorships', 'person_id')
    op.add_column('assembly_sponsorships', sa.Column('assembly_member_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.add_column('assembly_sponsorships', sa.Column('assembly_bill_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assembly_sponsorships', type_='foreignkey')
    op.drop_constraint(None, 'assembly_sponsorships', type_='foreignkey')
    op.create_foreign_key('assembly_sponsorships_assembly_bill_id_fkey', 'assembly_sponsorships', 'assembly_bills', ['assembly_bill_id'], ['bill_id'])
    op.create_foreign_key('assembly_sponsorships_assembly_member_id_fkey', 'assembly_sponsorships', 'assembly_members', ['assembly_member_id'], ['person_id'])
    op.drop_index(op.f('ix_assembly_sponsorships_person_id'), table_name='assembly_sponsorships')
    op.drop_index(op.f('ix_assembly_sponsorships_bill_id'), table_name='assembly_sponsorships')
    op.create_index('ix_assembly_sponsorships_assembly_member_id', 'assembly_sponsorships', ['assembly_member_id'], unique=False)
    op.create_index('ix_assembly_sponsorships_assembly_bill_id', 'assembly_sponsorships', ['assembly_bill_id'], unique=False)
    op.drop_column('assembly_sponsorships', 'bill_id')
    op.drop_column('assembly_sponsorships', 'person_id')
    # ### end Alembic commands ###
