"""state

Revision ID: 13c4b83caa05
Revises: 3e9adc79d05a
Create Date: 2021-12-27 18:36:04.832338

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '13c4b83caa05'
down_revision = '3e9adc79d05a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assembly_bills', 'summary')
    op.drop_column('senate_bills', 'summary')
    op.add_column('state_bills', sa.Column('summary', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state_bills', 'summary')
    op.add_column('senate_bills', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('assembly_bills', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
