"""Rename person to legislator

Revision ID: 174e0bf3a047
Revises: cd23f395aa99
Create Date: 2021-09-24 10:15:38.011954

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "174e0bf3a047"
down_revision = "cd23f395aa99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "legislators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "term_start", src.models.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "term_end", src.models.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column("email", sa.Text(), nullable=True),
        sa.Column("district_phone", sa.Text(), nullable=True),
        sa.Column("legislative_phone", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_table("persons")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "term_start",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "term_end",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "district_phone", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "legislative_phone", sa.TEXT(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name="persons_pkey"),
    )
    op.drop_table("legislators")
    # ### end Alembic commands ###
