"""Non null

Revision ID: 1a63719f0ca5
Revises: f4bab6d7405f
Create Date: 2022-01-03 04:31:19.243662

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a63719f0ca5'
down_revision = 'f4bab6d7405f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assembly_bills', 'bill_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.alter_column('senate_bills', 'bill_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('senate_bills', 'bill_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.alter_column('assembly_bills', 'bill_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    # ### end Alembic commands ###
