"""Add district code

Revision ID: 232c2c7b3fd1
Revises: 9b099aaf93e6
Create Date: 2022-01-03 20:46:41.255462

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "232c2c7b3fd1"
down_revision = "9b099aaf93e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assembly_members", sa.Column("district", sa.Integer(), nullable=True)
    )
    op.add_column(
        "senators", sa.Column("district", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("senators", "district")
    op.drop_column("assembly_members", "district")
    # ### end Alembic commands ###
