"""Add counties

Revision ID: 33963582a3d4
Revises: f3474239d289
Create Date: 2022-03-18 10:22:39.413775

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33963582a3d4'
down_revision = 'f3474239d289'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly_members', sa.Column('counties', postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column('senators', sa.Column('counties', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senators', 'counties')
    op.drop_column('assembly_members', 'counties')
    # ### end Alembic commands ###
