"""Add attachments

Revision ID: 3d1feaba64fb
Revises: 77c8cf31de2e
Create Date: 2021-09-24 17:40:22.033185

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '3d1feaba64fb'
down_revision = '77c8cf31de2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_attachments_bill_id'), 'bill_attachments', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bill_attachments_bill_id'), table_name='bill_attachments')
    op.drop_table('bill_attachments')
    # ### end Alembic commands ###
