"""Add summary

Revision ID: 3e9adc79d05a
Revises: 9bd5891aacf8
Create Date: 2021-12-27 18:33:31.039018

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '3e9adc79d05a'
down_revision = '9bd5891aacf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assembly_bills', sa.Column('summary', sa.Text(), nullable=False))
    op.add_column('senate_bills', sa.Column('summary', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('senate_bills', 'summary')
    op.drop_column('assembly_bills', 'summary')
    # ### end Alembic commands ###
