"""Add lead sponsor for state

Revision ID: 427207c44b00
Revises: 232c2c7b3fd1
Create Date: 2022-01-08 10:09:48.161696

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "427207c44b00"
down_revision = "232c2c7b3fd1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "assembly_sponsorships",
        sa.Column("is_lead_sponsor", sa.Boolean(), nullable=False),
    )
    op.add_column(
        "senate_sponsorships",
        sa.Column("is_lead_sponsor", sa.Boolean(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("senate_sponsorships", "is_lead_sponsor")
    op.drop_column("assembly_sponsorships", "is_lead_sponsor")
    # ### end Alembic commands ###
