"""Add council member website

Revision ID: 5028e522fd8d
Revises: 8b19a997a560
Create Date: 2021-09-24 22:04:08.113336

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '5028e522fd8d'
down_revision = '8b19a997a560'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislators', sa.Column('website', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislators', 'website')
    # ### end Alembic commands ###
