"""Add notes on legislators

Revision ID: 5f8320142f87
Revises: 5028e522fd8d
Create Date: 2021-09-26 19:31:16.513355

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "5f8320142f87"
down_revision = "5028e522fd8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("legislators", sa.Column("notes", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("legislators", "notes")
    # ### end Alembic commands ###
