"""Make bill/legislator a PK of sponsor

Revision ID: 68f88eb33d0a
Revises: 9c189abbeea7
Create Date: 2021-09-24 20:32:43.537047

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "68f88eb33d0a"
down_revision = "9c189abbeea7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_sponsorships2",
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("bill_id", "legislator_id"),
    )
    op.drop_index(
        "ix_bill_sponsorships_bill_id", table_name="bill_sponsorships"
    )
    op.drop_index(
        "ix_bill_sponsorships_legislator_id", table_name="bill_sponsorships"
    )
    op.drop_table("bill_sponsorships")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_sponsorships",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "bill_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "legislator_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["bill_id"], ["bills.id"], name="bill_sponsorships_bill_id_fkey"
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
            name="bill_sponsorships_legislator_id_fkey",
        ),
        sa.PrimaryKeyConstraint("id", name="bill_sponsorships_pkey"),
    )
    op.create_index(
        "ix_bill_sponsorships_legislator_id",
        "bill_sponsorships",
        ["legislator_id"],
        unique=False,
    )
    op.create_index(
        "ix_bill_sponsorships_bill_id",
        "bill_sponsorships",
        ["bill_id"],
        unique=False,
    )
    op.drop_table("bill_sponsorships2")
    # ### end Alembic commands ###
