"""Add sponsor sequence

Revision ID: 730353dab849
Revises: b343b7a84a2f
Create Date: 2021-11-24 12:16:19.696856

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "730353dab849"
down_revision = "b343b7a84a2f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_sponsorships",
        sa.Column("sponsor_sequence", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bill_sponsorships", "sponsor_sequence")
    # ### end Alembic commands ###
