"""Add sponsors

Revision ID: 77c8cf31de2e
Revises: a5ac81f7a47c
Create Date: 2021-09-24 14:20:33.858335

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "77c8cf31de2e"
down_revision = "a5ac81f7a47c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_sponsorships",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sa.Integer(), nullable=False),
        sa.Column("legislator_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["legislator_id"],
            ["legislators.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bill_sponsorships_bill_id"),
        "bill_sponsorships",
        ["bill_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bill_sponsorships_legislator_id"),
        "bill_sponsorships",
        ["legislator_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_bill_sponsorships_legislator_id"),
        table_name="bill_sponsorships",
    )
    op.drop_index(
        op.f("ix_bill_sponsorships_bill_id"), table_name="bill_sponsorships"
    )
    op.drop_table("bill_sponsorships")
    # ### end Alembic commands ###
