"""Rename bill sponsorships table again

Revision ID: 8b19a997a560
Revises: 68f88eb33d0a
Create Date: 2021-09-24 20:33:38.722973

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '8b19a997a560'
down_revision = '68f88eb33d0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_sponsorships',
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('legislator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'legislator_id')
    )
    op.drop_table('bill_sponsorships2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_sponsorships2',
    sa.Column('bill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('legislator_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name='bill_sponsorships2_bill_id_fkey'),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], name='bill_sponsorships2_legislator_id_fkey'),
    sa.PrimaryKeyConstraint('bill_id', 'legislator_id', name='bill_sponsorships2_pkey')
    )
    op.drop_table('bill_sponsorships')
    # ### end Alembic commands ###
