"""Add can_be_deleted to user

Revision ID: 8de472b6263e
Revises: e98054a3caaa
Create Date: 2021-10-05 13:44:50.442849

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '8de472b6263e'
down_revision = 'e98054a3caaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('can_be_deleted', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'can_be_deleted')
    # ### end Alembic commands ###
