"""Add twitter search terms

Revision ID: 96f760d6a424
Revises: cf09cc255323
Create Date: 2021-10-19 18:57:29.850688

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '96f760d6a424'
down_revision = 'cf09cc255323'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('custom_twitter_search_terms', postgresql.ARRAY(sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'custom_twitter_search_terms')
    # ### end Alembic commands ###
