"""Add council members

Revision ID: 98208cced6ea
Revises: d1be81e33696
Create Date: 2021-09-23 23:29:39.166460

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "98208cced6ea"
down_revision = "d1be81e33696"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "persons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column(
            "term_start", src.models.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.Column(
            "term_end", src.models.TIMESTAMP(timezone=True), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("persons")
    # ### end Alembic commands ###
