"""state impl

Revision ID: 9b099aaf93e6
Revises: 0b79940ebfd8
Create Date: 2022-01-03 15:55:32.842711

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b099aaf93e6'
down_revision = '0b79940ebfd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assembly_bills',
    sa.Column('active_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('base_print_no', sa.Text(), nullable=False),
    sa.Column('bill_id', src.models.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['state_bills.bill_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.create_table('senate_bills',
    sa.Column('active_version', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('base_print_no', sa.Text(), nullable=False),
    sa.Column('bill_id', src.models.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['state_bills.bill_id'], ),
    sa.PrimaryKeyConstraint('bill_id')
    )
    op.drop_index('ix_senate_bill_versions_bill_id', table_name='senate_bill_versions')
    op.drop_index('ix_assembly_bill_versions_bill_id', table_name='assembly_bill_versions')
    op.add_column('assembly_members', sa.Column('state_member_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'assembly_members', ['state_member_id'])
    op.add_column('assembly_sponsorships', sa.Column('assembly_bill_id', src.models.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_assembly_sponsorships_assembly_version_id', table_name='assembly_sponsorships')
    op.create_index(op.f('ix_assembly_sponsorships_assembly_bill_id'), 'assembly_sponsorships', ['assembly_bill_id'], unique=False)
    op.drop_constraint('assembly_sponsorships_assembly_version_id_fkey', 'assembly_sponsorships', type_='foreignkey')
    op.create_foreign_key(None, 'assembly_sponsorships', 'assembly_bills', ['assembly_bill_id'], ['bill_id'])
    op.drop_column('assembly_sponsorships', 'assembly_version_id')
    op.drop_index('ix_bill_attachments_2_bill_id', table_name='bill_attachments')
    op.create_index(op.f('ix_bill_attachments_bill_id'), 'bill_attachments', ['bill_id'], unique=False)
    op.add_column('bills', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('city_bills', 'title')
    op.drop_index('ix_power_hours_2_bill_id', table_name='power_hours')
    op.create_index(op.f('ix_power_hours_bill_id'), 'power_hours', ['bill_id'], unique=False)
    op.add_column('senate_sponsorships', sa.Column('senate_bill_id', src.models.UUID(as_uuid=True), nullable=False))
    op.drop_index('ix_senate_sponsorships_senate_version_id', table_name='senate_sponsorships')
    op.create_index(op.f('ix_senate_sponsorships_senate_bill_id'), 'senate_sponsorships', ['senate_bill_id'], unique=False)
    op.drop_constraint('senate_sponsorships_senate_version_id_fkey', 'senate_sponsorships', type_='foreignkey')
    op.create_foreign_key(None, 'senate_sponsorships', 'senate_bills', ['senate_bill_id'], ['bill_id'])
    op.drop_column('senate_sponsorships', 'senate_version_id')
    op.add_column('senators', sa.Column('state_member_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'senators', ['state_member_id'])
    op.drop_index('ix_staffers_2_boss_id', table_name='staffers')
    op.create_index(op.f('ix_staffers_boss_id'), 'staffers', ['boss_id'], unique=False)
    op.add_column('state_bills', sa.Column('session_year', sa.Integer(), nullable=False))

    op.drop_table('senate_bill_versions')
    op.drop_table('assembly_bill_versions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('state_bills', 'session_year')
    op.drop_index(op.f('ix_staffers_boss_id'), table_name='staffers')
    op.create_index('ix_staffers_2_boss_id', 'staffers', ['boss_id'], unique=False)
    op.drop_constraint(None, 'senators', type_='unique')
    op.drop_column('senators', 'state_member_id')
    op.add_column('senate_sponsorships', sa.Column('senate_version_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'senate_sponsorships', type_='foreignkey')
    op.create_foreign_key('senate_sponsorships_senate_version_id_fkey', 'senate_sponsorships', 'senate_bill_versions', ['senate_version_id'], ['id'])
    op.drop_index(op.f('ix_senate_sponsorships_senate_bill_id'), table_name='senate_sponsorships')
    op.create_index('ix_senate_sponsorships_senate_version_id', 'senate_sponsorships', ['senate_version_id'], unique=False)
    op.drop_column('senate_sponsorships', 'senate_bill_id')
    op.drop_index(op.f('ix_power_hours_bill_id'), table_name='power_hours')
    op.create_index('ix_power_hours_2_bill_id', 'power_hours', ['bill_id'], unique=False)
    op.add_column('city_bills', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('bills', 'description')
    op.drop_index(op.f('ix_bill_attachments_bill_id'), table_name='bill_attachments')
    op.create_index('ix_bill_attachments_2_bill_id', 'bill_attachments', ['bill_id'], unique=False)
    op.add_column('assembly_sponsorships', sa.Column('assembly_version_id', postgresql.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assembly_sponsorships', type_='foreignkey')
    op.create_foreign_key('assembly_sponsorships_assembly_version_id_fkey', 'assembly_sponsorships', 'assembly_bill_versions', ['assembly_version_id'], ['id'])
    op.drop_index(op.f('ix_assembly_sponsorships_assembly_bill_id'), table_name='assembly_sponsorships')
    op.create_index('ix_assembly_sponsorships_assembly_version_id', 'assembly_sponsorships', ['assembly_version_id'], unique=False)
    op.drop_column('assembly_sponsorships', 'assembly_bill_id')
    op.drop_constraint(None, 'assembly_members', type_='unique')
    op.drop_column('assembly_members', 'state_member_id')
    op.create_table('assembly_bill_versions',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('bill_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('version_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['state_bills.bill_id'], name='assembly_bill_versions_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='assembly_bill_versions_pkey')
    )
    op.create_index('ix_assembly_bill_versions_bill_id', 'assembly_bill_versions', ['bill_id'], unique=False)
    op.create_table('senate_bill_versions',
    sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False),
    sa.Column('bill_id', postgresql.UUID(), autoincrement=False, nullable=True),
    sa.Column('version_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['state_bills.bill_id'], name='senate_bill_versions_bill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='senate_bill_versions_pkey')
    )
    op.create_index('ix_senate_bill_versions_bill_id', 'senate_bill_versions', ['bill_id'], unique=False)
    op.drop_table('senate_bills')
    op.drop_table('assembly_bills')
    # ### end Alembic commands ###
