"""Add borough

Revision ID: 9c189abbeea7
Revises: 3d1feaba64fb
Create Date: 2021-09-24 19:59:55.770208

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = '9c189abbeea7'
down_revision = '3d1feaba64fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislators', sa.Column('borough', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislators', 'borough')
    # ### end Alembic commands ###
