"""Add nickname

Revision ID: a5ac81f7a47c
Revises: 5ab97f3a03d1
Create Date: 2021-09-24 13:58:04.228341

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'a5ac81f7a47c'
down_revision = '5ab97f3a03d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('nickname', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'nickname')
    # ### end Alembic commands ###
