"""Add committees

Revision ID: af095a2788ef
Revises: 9fd6c4dbc2fe
Create Date: 2022-01-15 17:20:23.296282

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'af095a2788ef'
down_revision = '9fd6c4dbc2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('council_bodies',
    sa.Column('id', src.models.UUID(as_uuid=True), nullable=False),
    sa.Column('council_body_id', sa.Integer(), nullable=False),
    sa.Column('body_type', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_council_bodies_council_body_id'), 'council_bodies', ['council_body_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_council_bodies_council_body_id'), table_name='council_bodies')
    op.drop_table('council_bodies')
    # ### end Alembic commands ###
