"""Small tweaks

Revision ID: afe83b657949
Revises: 1a63719f0ca5
Create Date: 2022-01-03 15:04:18.189936

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'afe83b657949'
down_revision = '1a63719f0ca5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assembly_members', ['state_member_id'])
    op.drop_column('assembly_members', 'state_person_id')
    op.create_unique_constraint(None, 'senators', ['state_member_id'])
    op.drop_column('senators', 'state_person_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('senators', sa.Column('state_person_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'senators', type_='unique')
    op.add_column('assembly_members', sa.Column('state_person_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'assembly_members', type_='unique')
    # ### end Alembic commands ###
