"""Add twitter search terms

Revision ID: b343b7a84a2f
Revises: cf09cc255323
Create Date: 2021-10-21 15:36:06.650875

"""
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "b343b7a84a2f"
down_revision = "cf09cc255323"
branch_labels = None
depends_on = None

DEFAULT_TWITTER_SEARCH_TERMS = [
    "solar",
    "climate",
    "wind power",
    "renewable",
    "fossil fuel",
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bills",
        sa.Column(
            "twitter_search_terms", postgresql.ARRAY(sa.Text()), nullable=True
        ),
    )
    bills_table = sa.sql.table(
        "bills", sa.Column("twitter_search_terms", postgresql.ARRAY(sa.Text()))
    )
    op.execute(
        bills_table.update().values(
            twitter_search_terms=DEFAULT_TWITTER_SEARCH_TERMS
        )
    )
    op.alter_column(
        "bills",
        "twitter_search_terms",
        existing_type=postgresql.ARRAY(sa.Text()),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "twitter_search_terms")
    # ### end Alembic commands ###
