"""Add staffers

Revision ID: c0a643362ad9
Revises: 419caf2c892b
Create Date: 2021-10-05 22:23:48.754242

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'c0a643362ad9'
down_revision = '419caf2c892b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staffers',
    sa.Column('id', src.models.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('legislator_id', sa.Integer(), nullable=False),
    sa.Column('twitter', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['legislator_id'], ['legislators.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staffers')
    # ### end Alembic commands ###
