"""Move notification settings to user-bill pair

Revision ID: c8f2969150b7
Revises: 9fd6c4dbc2fe
Create Date: 2022-01-31 16:47:51.727885

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'c8f2969150b7'
down_revision = '9fd6c4dbc2fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_bill_settings',
    sa.Column('bill_id', src.models.UUID(as_uuid=True), nullable=False),
    sa.Column('user_id', src.models.UUID(as_uuid=True), nullable=False),
    sa.Column('send_bill_update_notifications', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('bill_id', 'user_id')
    )
    op.drop_index('ix_users_send_bill_update_notifications', table_name='users')
    op.drop_column('users', 'send_bill_update_notifications')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('send_bill_update_notifications', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.create_index('ix_users_send_bill_update_notifications', 'users', ['send_bill_update_notifications'], unique=False)
    op.drop_table('user_bill_settings')
    # ### end Alembic commands ###
