"""Separate out power hour from attachemtns in model

Revision ID: cb9ba28ca160
Revises: 730353dab849
Create Date: 2021-12-02 17:21:08.052682

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'cb9ba28ca160'
down_revision = '730353dab849'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('power_hours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('spreadsheet_url', sa.Text(), nullable=False),
    sa.Column('spreadsheet_id', sa.Text(), nullable=False),
    sa.Column('created_at', src.models.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_power_hours_bill_id'), 'power_hours', ['bill_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_power_hours_bill_id'), table_name='power_hours')
    op.drop_table('power_hours')
    # ### end Alembic commands ###
