"""Add person contact info

Revision ID: cd23f395aa99
Revises: 98208cced6ea
Create Date: 2021-09-24 08:58:24.837373

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "cd23f395aa99"
down_revision = "98208cced6ea"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("persons", sa.Column("email", sa.Text(), nullable=True))
    op.add_column(
        "persons", sa.Column("district_phone", sa.Text(), nullable=True)
    )
    op.add_column(
        "persons", sa.Column("legislative_phone", sa.Text(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("persons", "legislative_phone")
    op.drop_column("persons", "district_phone")
    op.drop_column("persons", "email")
    # ### end Alembic commands ###
