"""Email notifications for bill updates

Revision ID: cf09cc255323
Revises: c0a643362ad9
Create Date: 2021-10-12 10:04:14.243671

"""
import sqlalchemy as sa

import src
from alembic import op

# revision identifiers, used by Alembic.
revision = "cf09cc255323"
down_revision = "c0a643362ad9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bill_sponsorships",
        sa.Column(
            "added_at", src.models.TIMESTAMP(timezone=True), nullable=True
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "send_bill_update_notifications",
            sa.Boolean(),
            server_default=sa.text("false"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_users_send_bill_update_notifications"),
        "users",
        ["send_bill_update_notifications"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_users_send_bill_update_notifications"), table_name="users"
    )
    op.drop_column("users", "send_bill_update_notifications")
    op.drop_column("bill_sponsorships", "added_at")
    # ### end Alembic commands ###
