"""Add twitter

Revision ID: cf8896090d1d
Revises: 5f8320142f87
Create Date: 2021-09-27 15:52:14.632340

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'cf8896090d1d'
down_revision = '5f8320142f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('legislators', sa.Column('twitter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('legislators', 'twitter')
    # ### end Alembic commands ###
