"""Remove used_at

Revision ID: f3474239d289
Revises: 1bcff1e81e30
Create Date: 2022-03-13 13:13:10.707526

"""
from alembic import op
import sqlalchemy as sa
import src
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3474239d289'
down_revision = '1bcff1e81e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('login_links', 'used_at')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('login_links', sa.Column('used_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
