"""move some fields

Revision ID: f4bab6d7405f
Revises: 13c4b83caa05
Create Date: 2021-12-28 18:45:31.704682

"""
from alembic import op
import sqlalchemy as sa
import src


# revision identifiers, used by Alembic.
revision = 'f4bab6d7405f'
down_revision = '13c4b83caa05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('description', sa.Text(), nullable=False))
    op.drop_column('city_bills', 'title')
    op.drop_column('state_bills', 'summary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('state_bills', sa.Column('summary', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('city_bills', sa.Column('title', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('bills', 'description')
    # ### end Alembic commands ###
